server:
  port: ${PORT:8888}
  servlet:
    context-path: /config
management:
  endpoints:
    web:
      exposure:
        include: health,info,env

spring:
  profiles:
    active: ${PROFILE:local}
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/saadahmad5/ConfigServiceConfigurations.git"
          search-paths: "{application}"
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          skip-ssl-validation: true
          force-pull: true
          default-label: ${BRANCH:main}